name: Build Savannah Daily Briefing

on:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC = 6:00 AM ET during DST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build & publish briefing
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_PREFIX: ${{ secrets.S3_PREFIX }}
          POLLY_VOICE: ${{ secrets.POLLY_VOICE }}
run: |
  python -m scripts.build_briefing

      - name: Commit updated feed & script
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add savannah-daily-briefing-feed.json latest-script.txt
          git commit -m "Daily feed update" || echo "No changes"
          git push
